services:
  nginx:
    image: nginx:alpine
    container_name: nikola_app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot:latest
    container_name: nikola_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ""
    command: >
      sh -c "trap exit TERM;
      while :; do
      certbot renew --webroot -w /var/www/certbot --quiet;
      sleep 12h;
      done"